"""
Type definitions for MED13 Resource Library.

This module contains all type definitions used throughout the application,
organized by domain and usage pattern.
"""

from .authorization import (
    AccessCheckResponse,
    RoleCapabilitiesResponse,
    RolePermissionsSummary,
    SystemPermissionsSummary,
)
from .common import (
    APIResponse,
    EvidenceUpdate,
    GeneUpdate,
    PaginatedResponse,
    PhenotypeUpdate,
    PublicationUpdate,
    RawRecord,
    ValidationResult,
    VariantUpdate,
)
from .confidence import ConfidenceExtras, ConfidenceScoreOptions
from .curation import ReviewRecordLike
from .data_sources import (
    DataSourceAiTestFinding,
    DataSourceAiTestLink,
    DataSourceAiTestResult,
    FlujoTableSummary,
    SourceCatalogEntrySeed,
)
from .external_apis import (
    ClinVarSearchResponse,
    ClinVarVariantResponse,
    HPOOntologyResponse,
    PubMedArticleResponse,
    PubMedSearchResponse,
    UniProtEntryResponse,
)
from .packaging import (
    ComplianceSection,
    DatasetMetadataOptions,
    LicenseInfo,
    LicenseManifest,
    LicenseRecord,
    LicenseSourceEntry,
    LicenseValidationResult,
    ProvenanceMetadata,
    ProvenanceSourceEntry,
    ROCrateFileEntry,
    ROCrateFileEntryRequired,
)
from .publishing import DOIMintResult
from .repositories import (
    GeneStatistics,
    SourceTemplateStatistics,
    UserDataSourceStatistics,
)
from .search import RawSearchResult, UnifiedSearchPayload
from .security import (
    DecodedTokenPayload,
    HashInfo,
    PasswordAnalysis,
    RefreshResult,
    TokenPayload,
)
from .storage import (
    GoogleCloudStorageConfig,
    LocalFilesystemConfig,
    SignedUrlRequest,
    StorageConfigurationModel,
    StorageHealthReport,
    StorageHealthStatus,
    StorageOperationRecord,
    StorageOperationStatus,
    StorageOperationType,
    StorageProviderCapability,
    StorageProviderConfig,
    StorageProviderConfigModel,
    StorageProviderMetadata,
    StorageProviderName,
    StorageProviderTestResult,
    StorageUrlModel,
    StorageUsageMetrics,
    StorageUseCase,
)
from .system_status import (
    EnableMaintenanceRequest,
    MaintenanceModeResponse,
    MaintenanceModeState,
)

__all__ = [
    "APIResponse",
    "AccessCheckResponse",
    "ClinVarSearchResponse",
    "ClinVarVariantResponse",
    "ComplianceSection",
    "ConfidenceExtras",
    "ConfidenceScoreOptions",
    "DataSourceAiTestFinding",
    "DataSourceAiTestLink",
    "DataSourceAiTestResult",
    "DatasetMetadataOptions",
    "DecodedTokenPayload",
    "DOIMintResult",
    "FlujoTableSummary",
    "EvidenceUpdate",
    "GeneUpdate",
    "GeneStatistics",
    "GoogleCloudStorageConfig",
    "HashInfo",
    "HPOOntologyResponse",
    "LicenseInfo",
    "LicenseManifest",
    "LicenseRecord",
    "LicenseSourceEntry",
    "LicenseValidationResult",
    "LocalFilesystemConfig",
    "PaginatedResponse",
    "PasswordAnalysis",
    "PhenotypeUpdate",
    "ProvenanceMetadata",
    "ProvenanceSourceEntry",
    "PubMedArticleResponse",
    "PubMedSearchResponse",
    "PublicationUpdate",
    "RawSearchResult",
    "RawRecord",
    "RefreshResult",
    "ReviewRecordLike",
    "RoleCapabilitiesResponse",
    "RolePermissionsSummary",
    "ROCrateFileEntry",
    "ROCrateFileEntryRequired",
    "SignedUrlRequest",
    "SourceCatalogEntrySeed",
    "SourceTemplateStatistics",
    "StorageConfigurationModel",
    "StorageHealthReport",
    "StorageHealthStatus",
    "StorageOperationRecord",
    "StorageOperationStatus",
    "StorageOperationType",
    "StorageProviderCapability",
    "StorageProviderConfig",
    "StorageProviderConfigModel",
    "StorageProviderMetadata",
    "StorageProviderName",
    "StorageProviderTestResult",
    "StorageUrlModel",
    "StorageUsageMetrics",
    "StorageUseCase",
    "SystemPermissionsSummary",
    "EnableMaintenanceRequest",
    "MaintenanceModeResponse",
    "MaintenanceModeState",
    "TokenPayload",
    "UniProtEntryResponse",
    "UnifiedSearchPayload",
    "UserDataSourceStatistics",
    "ValidationResult",
    "VariantUpdate",
]
