"""
Type definitions for MED13 Resource Library.

This module contains all type definitions used throughout the application,
organized by domain and usage pattern.
"""

from .common import (
    APIResponse,
    EvidenceUpdate,
    GeneUpdate,
    PaginatedResponse,
    PhenotypeUpdate,
    PublicationUpdate,
    RawRecord,
    ValidationResult,
    VariantUpdate,
)
from .external_apis import (
    ClinVarSearchResponse,
    ClinVarVariantResponse,
    HPOOntologyResponse,
    PubMedArticleResponse,
    PubMedSearchResponse,
    UniProtEntryResponse,
)
from .storage import (
    GoogleCloudStorageConfig,
    LocalFilesystemConfig,
    SignedUrlRequest,
    StorageConfigurationModel,
    StorageHealthReport,
    StorageHealthStatus,
    StorageOperationRecord,
    StorageOperationStatus,
    StorageOperationType,
    StorageProviderCapability,
    StorageProviderConfig,
    StorageProviderConfigModel,
    StorageProviderMetadata,
    StorageProviderName,
    StorageProviderTestResult,
    StorageUrlModel,
    StorageUsageMetrics,
    StorageUseCase,
)

__all__ = [
    "APIResponse",
    "ClinVarSearchResponse",
    "ClinVarVariantResponse",
    "EvidenceUpdate",
    "GeneUpdate",
    "GoogleCloudStorageConfig",
    "HPOOntologyResponse",
    "LocalFilesystemConfig",
    "PaginatedResponse",
    "PhenotypeUpdate",
    "PubMedArticleResponse",
    "PubMedSearchResponse",
    "PublicationUpdate",
    "RawRecord",
    "SignedUrlRequest",
    "StorageConfigurationModel",
    "StorageHealthReport",
    "StorageHealthStatus",
    "StorageOperationRecord",
    "StorageOperationStatus",
    "StorageOperationType",
    "StorageProviderCapability",
    "StorageProviderConfig",
    "StorageProviderConfigModel",
    "StorageProviderMetadata",
    "StorageProviderName",
    "StorageProviderTestResult",
    "StorageUrlModel",
    "StorageUsageMetrics",
    "StorageUseCase",
    "UniProtEntryResponse",
    "ValidationResult",
    "VariantUpdate",
]
