"""Initial database schema

Revision ID: a672f05b90d4
Revises:
Create Date: 2025-11-01 14:14:35.312881

"""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa

from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "a672f05b90d4"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "genes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("gene_id", sa.String(length=50), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("gene_type", sa.String(length=20), nullable=False),
        sa.Column("chromosome", sa.String(length=10), nullable=True),
        sa.Column("start_position", sa.Integer(), nullable=True),
        sa.Column("end_position", sa.Integer(), nullable=True),
        sa.Column("ensembl_id", sa.String(length=20), nullable=True),
        sa.Column("ncbi_gene_id", sa.Integer(), nullable=True),
        sa.Column("uniprot_id", sa.String(length=20), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_genes")),
        sqlite_autoincrement=True,
    )
    op.create_index(op.f("ix_genes_ensembl_id"), "genes", ["ensembl_id"], unique=True)
    op.create_index(op.f("ix_genes_gene_id"), "genes", ["gene_id"], unique=True)
    op.create_index(
        op.f("ix_genes_ncbi_gene_id"),
        "genes",
        ["ncbi_gene_id"],
        unique=True,
    )
    op.create_index(op.f("ix_genes_symbol"), "genes", ["symbol"], unique=True)
    op.create_index(op.f("ix_genes_uniprot_id"), "genes", ["uniprot_id"], unique=True)
    op.create_table(
        "phenotypes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("hpo_id", sa.String(length=20), nullable=False),
        sa.Column("hpo_term", sa.String(length=200), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("definition", sa.Text(), nullable=True),
        sa.Column("synonyms", sa.Text(), nullable=True),
        sa.Column(
            "category",
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column("parent_hpo_id", sa.String(length=20), nullable=True),
        sa.Column("is_root_term", sa.Boolean(), nullable=False),
        sa.Column("frequency_in_med13", sa.String(length=100), nullable=True),
        sa.Column("severity_score", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_phenotypes")),
        sqlite_autoincrement=True,
    )
    op.create_index(op.f("ix_phenotypes_hpo_id"), "phenotypes", ["hpo_id"], unique=True)
    op.create_index(
        op.f("ix_phenotypes_hpo_term"),
        "phenotypes",
        ["hpo_term"],
        unique=False,
    )
    op.create_index(
        op.f("ix_phenotypes_parent_hpo_id"),
        "phenotypes",
        ["parent_hpo_id"],
        unique=False,
    )
    op.create_table(
        "publications",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("pubmed_id", sa.String(length=20), nullable=True),
        sa.Column("pmc_id", sa.String(length=20), nullable=True),
        sa.Column("doi", sa.String(length=100), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("authors", sa.Text(), nullable=False),
        sa.Column("journal", sa.String(length=200), nullable=False),
        sa.Column("publication_year", sa.Integer(), nullable=False),
        sa.Column("volume", sa.String(length=20), nullable=True),
        sa.Column("issue", sa.String(length=20), nullable=True),
        sa.Column("pages", sa.String(length=50), nullable=True),
        sa.Column("publication_date", sa.Date(), nullable=True),
        sa.Column(
            "publication_type",
            sa.String(length=30),
            nullable=False,
        ),
        sa.Column("abstract", sa.Text(), nullable=True),
        sa.Column("keywords", sa.Text(), nullable=True),
        sa.Column("citation_count", sa.Integer(), nullable=True),
        sa.Column("impact_factor", sa.Float(), nullable=True),
        sa.Column("reviewed", sa.Boolean(), nullable=False),
        sa.Column("relevance_score", sa.Integer(), nullable=True),
        sa.Column("full_text_url", sa.String(length=500), nullable=True),
        sa.Column("open_access", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_publications")),
        sqlite_autoincrement=True,
    )
    op.create_index(op.f("ix_publications_doi"), "publications", ["doi"], unique=True)
    op.create_index(
        op.f("ix_publications_pmc_id"),
        "publications",
        ["pmc_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_publications_publication_year"),
        "publications",
        ["publication_year"],
        unique=False,
    )
    op.create_index(
        op.f("ix_publications_pubmed_id"),
        "publications",
        ["pubmed_id"],
        unique=True,
    )
    op.create_table(
        "variants",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("gene_id", sa.Integer(), nullable=False),
        sa.Column("variant_id", sa.String(length=100), nullable=False),
        sa.Column("clinvar_id", sa.String(length=20), nullable=True),
        sa.Column("chromosome", sa.String(length=10), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("reference_allele", sa.String(length=1000), nullable=False),
        sa.Column("alternate_allele", sa.String(length=1000), nullable=False),
        sa.Column("hgvs_genomic", sa.String(length=500), nullable=True),
        sa.Column("hgvs_protein", sa.String(length=500), nullable=True),
        sa.Column("hgvs_cdna", sa.String(length=500), nullable=True),
        sa.Column("variant_type", sa.String(length=20), nullable=False),
        sa.Column(
            "clinical_significance",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column("condition", sa.String(length=500), nullable=True),
        sa.Column("review_status", sa.String(length=100), nullable=True),
        sa.Column("allele_frequency", sa.Float(), nullable=True),
        sa.Column("gnomad_af", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["gene_id"],
            ["genes.id"],
            name=op.f("fk_variants_gene_id_genes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_variants")),
        sqlite_autoincrement=True,
    )
    op.create_index(
        op.f("ix_variants_clinvar_id"),
        "variants",
        ["clinvar_id"],
        unique=True,
    )
    op.create_index(op.f("ix_variants_gene_id"), "variants", ["gene_id"], unique=False)
    op.create_index(
        op.f("ix_variants_position"),
        "variants",
        ["position"],
        unique=False,
    )
    op.create_index(
        op.f("ix_variants_variant_id"),
        "variants",
        ["variant_id"],
        unique=True,
    )
    op.create_table(
        "evidence",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("variant_id", sa.Integer(), nullable=False),
        sa.Column("phenotype_id", sa.Integer(), nullable=False),
        sa.Column("publication_id", sa.Integer(), nullable=True),
        sa.Column(
            "evidence_level",
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column("evidence_type", sa.String(length=30), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column("quality_score", sa.Integer(), nullable=True),
        sa.Column("sample_size", sa.Integer(), nullable=True),
        sa.Column("study_type", sa.String(length=100), nullable=True),
        sa.Column("statistical_significance", sa.String(length=50), nullable=True),
        sa.Column("reviewed", sa.Boolean(), nullable=False),
        sa.Column("review_date", sa.Date(), nullable=True),
        sa.Column("reviewer_notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["phenotype_id"],
            ["phenotypes.id"],
            name=op.f("fk_evidence_phenotype_id_phenotypes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["publication_id"],
            ["publications.id"],
            name=op.f("fk_evidence_publication_id_publications"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["variants.id"],
            name=op.f("fk_evidence_variant_id_variants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence")),
        sqlite_autoincrement=True,
    )
    op.create_index(
        op.f("ix_evidence_phenotype_id"),
        "evidence",
        ["phenotype_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evidence_publication_id"),
        "evidence",
        ["publication_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evidence_variant_id"),
        "evidence",
        ["variant_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_evidence_variant_id"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_publication_id"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_phenotype_id"), table_name="evidence")
    op.drop_table("evidence")
    op.drop_index(op.f("ix_variants_variant_id"), table_name="variants")
    op.drop_index(op.f("ix_variants_position"), table_name="variants")
    op.drop_index(op.f("ix_variants_gene_id"), table_name="variants")
    op.drop_index(op.f("ix_variants_clinvar_id"), table_name="variants")
    op.drop_table("variants")
    op.drop_index(op.f("ix_publications_pubmed_id"), table_name="publications")
    op.drop_index(op.f("ix_publications_publication_year"), table_name="publications")
    op.drop_index(op.f("ix_publications_pmc_id"), table_name="publications")
    op.drop_index(op.f("ix_publications_doi"), table_name="publications")
    op.drop_table("publications")
    op.drop_index(op.f("ix_phenotypes_parent_hpo_id"), table_name="phenotypes")
    op.drop_index(op.f("ix_phenotypes_hpo_term"), table_name="phenotypes")
    op.drop_index(op.f("ix_phenotypes_hpo_id"), table_name="phenotypes")
    op.drop_table("phenotypes")
    op.drop_index(op.f("ix_genes_uniprot_id"), table_name="genes")
    op.drop_index(op.f("ix_genes_symbol"), table_name="genes")
    op.drop_index(op.f("ix_genes_ncbi_gene_id"), table_name="genes")
    op.drop_index(op.f("ix_genes_gene_id"), table_name="genes")
    op.drop_index(op.f("ix_genes_ensembl_id"), table_name="genes")
    op.drop_table("genes")
    # ### end Alembic commands ###
