"""Add research spaces tables

Revision ID: f251af2b636a
Revises: fe86208f6b48
Create Date: 2025-11-06 22:59:16.906054

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from src.models.database.research_space import (
    MembershipRoleEnum,
    SpaceStatusEnum,
)

# revision identifiers, used by Alembic.
revision: str = "f251af2b636a"
down_revision: str | Sequence[str] | None = "fe86208f6b48"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "research_spaces",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(SpaceStatusEnum, name="space_status_enum"),
            nullable=False,
        ),
        sa.Column("settings", sa.JSON(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_research_spaces_owner_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_spaces")),
        comment="Research spaces for multi-tenancy support",
    )
    op.create_index(
        "idx_research_spaces_created_at",
        "research_spaces",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "idx_research_spaces_owner",
        "research_spaces",
        ["owner_id"],
        unique=False,
    )
    op.create_index(
        "idx_research_spaces_status",
        "research_spaces",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_spaces_slug"),
        "research_spaces",
        ["slug"],
        unique=True,
    )
    op.create_table(
        "research_space_memberships",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("space_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(MembershipRoleEnum, name="membership_role_enum"),
            nullable=False,
        ),
        sa.Column("invited_by", sa.UUID(), nullable=True),
        sa.Column("invited_at", sa.DateTime(), nullable=True),
        sa.Column("joined_at", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["invited_by"],
            ["users.id"],
            name=op.f("fk_research_space_memberships_invited_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["space_id"],
            ["research_spaces.id"],
            name=op.f("fk_research_space_memberships_space_id_research_spaces"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_research_space_memberships_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_space_memberships")),
        comment="Research space memberships for role-based access control",
    )
    op.create_index(
        "idx_memberships_invited_by",
        "research_space_memberships",
        ["invited_by"],
        unique=False,
    )
    op.create_index(
        "idx_memberships_pending",
        "research_space_memberships",
        ["user_id", "invited_at", "joined_at"],
        unique=False,
    )
    op.create_index(
        "idx_memberships_space",
        "research_space_memberships",
        ["space_id"],
        unique=False,
    )
    op.create_index(
        "idx_memberships_space_user",
        "research_space_memberships",
        ["space_id", "user_id"],
        unique=True,
    )
    op.create_index(
        "idx_memberships_user",
        "research_space_memberships",
        ["user_id"],
        unique=False,
    )
    op.drop_index(op.f("idx_sessions_active_only"), table_name="sessions")
    op.drop_index(op.f("idx_sessions_expired_cleanup"), table_name="sessions")
    op.drop_index(op.f("idx_sessions_expires_at"), table_name="sessions")
    op.drop_index(op.f("idx_sessions_ip_address"), table_name="sessions")
    op.drop_index(op.f("idx_sessions_last_activity"), table_name="sessions")
    op.drop_index(op.f("idx_sessions_refresh_expires"), table_name="sessions")
    op.drop_index(op.f("idx_sessions_user_status"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_expires_at"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_status"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_table("sessions")
    op.alter_column(
        "ingestion_jobs",
        "id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(as_uuid=False),
        existing_nullable=False,
    )
    op.alter_column(
        "ingestion_jobs",
        "source_id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(as_uuid=False),
        existing_nullable=False,
    )
    op.alter_column(
        "ingestion_jobs",
        "triggered_by",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(as_uuid=False),
        existing_nullable=True,
    )
    op.alter_column(
        "source_templates",
        "id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(as_uuid=False),
        existing_nullable=False,
    )
    op.alter_column(
        "source_templates",
        "created_by",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(as_uuid=False),
        existing_nullable=False,
    )
    op.add_column(
        "user_data_sources",
        sa.Column("research_space_id", sa.UUID(as_uuid=False), nullable=True),
    )
    op.alter_column(
        "user_data_sources",
        "id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(as_uuid=False),
        existing_nullable=False,
    )
    op.alter_column(
        "user_data_sources",
        "owner_id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(as_uuid=False),
        existing_nullable=False,
    )
    op.alter_column(
        "user_data_sources",
        "template_id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(as_uuid=False),
        existing_nullable=True,
    )
    op.create_index(
        op.f("ix_user_data_sources_research_space_id"),
        "user_data_sources",
        ["research_space_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_user_data_sources_research_space_id_research_spaces"),
        "user_data_sources",
        "research_spaces",
        ["research_space_id"],
        ["id"],
    )
    op.alter_column(
        "users",
        "id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.drop_constraint(
        op.f("fk_user_data_sources_research_space_id_research_spaces"),
        "user_data_sources",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("ix_user_data_sources_research_space_id"),
        table_name="user_data_sources",
    )
    op.alter_column(
        "user_data_sources",
        "template_id",
        existing_type=sa.UUID(as_uuid=False),
        type_=sa.NUMERIC(),
        existing_nullable=True,
    )
    op.alter_column(
        "user_data_sources",
        "owner_id",
        existing_type=sa.UUID(as_uuid=False),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "user_data_sources",
        "id",
        existing_type=sa.UUID(as_uuid=False),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.drop_column("user_data_sources", "research_space_id")
    op.alter_column(
        "source_templates",
        "created_by",
        existing_type=sa.UUID(as_uuid=False),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "source_templates",
        "id",
        existing_type=sa.UUID(as_uuid=False),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "ingestion_jobs",
        "triggered_by",
        existing_type=sa.UUID(as_uuid=False),
        type_=sa.NUMERIC(),
        existing_nullable=True,
    )
    op.alter_column(
        "ingestion_jobs",
        "source_id",
        existing_type=sa.UUID(as_uuid=False),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "ingestion_jobs",
        "id",
        existing_type=sa.UUID(as_uuid=False),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.NUMERIC(), nullable=False),
        sa.Column("user_id", sa.NUMERIC(), nullable=False),
        sa.Column("session_token", sa.TEXT(), nullable=False),
        sa.Column("refresh_token", sa.TEXT(), nullable=False),
        sa.Column("ip_address", sa.VARCHAR(length=45), nullable=True),
        sa.Column("user_agent", sa.TEXT(), nullable=True),
        sa.Column("device_fingerprint", sa.VARCHAR(length=32), nullable=True),
        sa.Column("status", sa.VARCHAR(length=7), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("refresh_expires_at", sa.TIMESTAMP(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("'NOW()'"),
            nullable=False,
        ),
        sa.Column(
            "last_activity",
            sa.TIMESTAMP(),
            server_default=sa.text("'NOW()'"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
    )
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_index(op.f("ix_sessions_status"), "sessions", ["status"], unique=False)
    op.create_index(
        op.f("ix_sessions_expires_at"),
        "sessions",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("idx_sessions_user_status"),
        "sessions",
        ["user_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("idx_sessions_refresh_expires"),
        "sessions",
        ["refresh_expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("idx_sessions_last_activity"),
        "sessions",
        ["last_activity"],
        unique=False,
    )
    op.create_index(
        op.f("idx_sessions_ip_address"),
        "sessions",
        ["ip_address"],
        unique=False,
    )
    op.create_index(
        op.f("idx_sessions_expires_at"),
        "sessions",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("idx_sessions_expired_cleanup"),
        "sessions",
        ["created_at"],
        unique=False,
    )
    op.create_index(op.f("idx_sessions_active_only"), "sessions", ["id"], unique=False)
    op.drop_index("idx_memberships_user", table_name="research_space_memberships")
    op.drop_index("idx_memberships_space_user", table_name="research_space_memberships")
    op.drop_index("idx_memberships_space", table_name="research_space_memberships")
    op.drop_index("idx_memberships_pending", table_name="research_space_memberships")
    op.drop_index("idx_memberships_invited_by", table_name="research_space_memberships")
    op.drop_table("research_space_memberships")
    op.drop_index(op.f("ix_research_spaces_slug"), table_name="research_spaces")
    op.drop_index("idx_research_spaces_status", table_name="research_spaces")
    op.drop_index("idx_research_spaces_owner", table_name="research_spaces")
    op.drop_index("idx_research_spaces_created_at", table_name="research_spaces")
    op.drop_table("research_spaces")
    # ### end Alembic commands ###
