// Auto-generated by scripts/generate_ts_types.py. Do not edit.
/* eslint-disable */
/* prettier-ignore */

export interface ErrorDetail {
  field?: string | null;
  message: string;
  code?: string | null;
}

export interface ErrorResponse {
  error: string;
  message: string;
  details?: ErrorDetail[] | null;
  request_id?: string | null;
}

export interface HealthComponent {
  status: string;
  message?: string | null;
  details?: Record<string, unknown> | null;
}

export interface HealthResponse {
  status: string;
  timestamp: string;
  version: string;
  uptime?: string | null;
  components?: Record<string, HealthComponent> | null;
}

export interface PaginatedResponse {
  items: unknown[];
  total: number;
  page: number;
  per_page: number;
  total_pages: number;
  has_next: boolean;
  has_prev: boolean;
}

export interface PaginationParams {
  page?: number;
  per_page?: number;
  sort_by?: string | null;
  sort_order?: string;
}

export interface EvidenceCreate {
  variant_id: string;
  phenotype_id: string;
  description: string;
  summary?: string | null;
  evidence_level?: 'definitive' | 'strong' | 'moderate' | 'supporting' | 'weak' | 'disproven';
  evidence_type?: 'clinical_report' | 'functional_study' | 'animal_model' | 'biochemical' | 'computational' | 'literature_review' | 'expert_opinion';
  publication_id?: string | null;
  confidence_score?: number;
  quality_score?: number | null;
  sample_size?: number | null;
  study_type?: string | null;
  statistical_significance?: string | null;
  reviewed?: boolean;
  review_date?: string | null;
  reviewer_notes?: string | null;
}

export interface EvidenceResponse {
  id: number;
  variant_id: string;
  phenotype_id: string;
  publication_id?: string | null;
  description: string;
  summary?: string | null;
  evidence_level: 'definitive' | 'strong' | 'moderate' | 'supporting' | 'weak' | 'disproven';
  evidence_type: 'clinical_report' | 'functional_study' | 'animal_model' | 'biochemical' | 'computational' | 'literature_review' | 'expert_opinion';
  confidence_score: number;
  quality_score?: number | null;
  sample_size?: number | null;
  study_type?: string | null;
  statistical_significance?: string | null;
  reviewed: boolean;
  review_date?: string | null;
  reviewer_notes?: string | null;
  created_at: string;
  updated_at: string;
  variant?: Record<string, unknown> | null;
  phenotype?: Record<string, unknown> | null;
  publication?: Record<string, unknown> | null;
}

export interface EvidenceUpdate {
  description?: string | null;
  summary?: string | null;
  evidence_level?: 'definitive' | 'strong' | 'moderate' | 'supporting' | 'weak' | 'disproven' | null;
  evidence_type?: 'clinical_report' | 'functional_study' | 'animal_model' | 'biochemical' | 'computational' | 'literature_review' | 'expert_opinion' | null;
  publication_id?: string | null;
  confidence_score?: number | null;
  quality_score?: number | null;
  sample_size?: number | null;
  study_type?: string | null;
  statistical_significance?: string | null;
  reviewed?: boolean | null;
  review_date?: string | null;
  reviewer_notes?: string | null;
}

export interface GeneCreate {
  symbol: string;
  name?: string | null;
  description?: string | null;
  gene_type?: 'protein_coding' | 'pseudogene' | 'ncRNA' | 'unknown';
  chromosome?: string | null;
  start_position?: number | null;
  end_position?: number | null;
  ensembl_id?: string | null;
  ncbi_gene_id?: number | null;
  uniprot_id?: string | null;
}

export interface GeneResponse {
  id: number;
  gene_id: string;
  symbol: string;
  name?: string | null;
  description?: string | null;
  gene_type: 'protein_coding' | 'pseudogene' | 'ncRNA' | 'unknown';
  chromosome?: string | null;
  start_position?: number | null;
  end_position?: number | null;
  ensembl_id?: string | null;
  ncbi_gene_id?: number | null;
  uniprot_id?: string | null;
  created_at: string;
  updated_at: string;
  variant_count?: number;
  phenotype_count?: number;
  variants?: Record<string, unknown>[] | null;
  phenotypes?: Record<string, unknown>[] | null;
}

export interface GeneUpdate {
  name?: string | null;
  description?: string | null;
  gene_type?: 'protein_coding' | 'pseudogene' | 'ncRNA' | 'unknown' | null;
  chromosome?: string | null;
  start_position?: number | null;
  end_position?: number | null;
  ensembl_id?: string | null;
  ncbi_gene_id?: number | null;
  uniprot_id?: string | null;
}

export interface PhenotypeCreate {
  hpo_id: string;
  hpo_term: string;
  name: string;
  definition?: string | null;
  synonyms?: string[] | null;
  category?: 'congenital' | 'developmental' | 'neurological' | 'cardiovascular' | 'musculoskeletal' | 'endocrine' | 'immunological' | 'oncological' | 'other';
  parent_hpo_id?: string | null;
  is_root_term?: boolean;
  frequency_in_med13?: string | null;
  severity_score?: number | null;
}

export interface PhenotypeResponse {
  id: number;
  hpo_id: string;
  hpo_term: string;
  name: string;
  definition?: string | null;
  synonyms?: string[] | null;
  category: 'congenital' | 'developmental' | 'neurological' | 'cardiovascular' | 'musculoskeletal' | 'endocrine' | 'immunological' | 'oncological' | 'other';
  parent_hpo_id?: string | null;
  is_root_term: boolean;
  frequency_in_med13?: string | null;
  severity_score?: number | null;
  created_at: string;
  updated_at: string;
  evidence_count?: number;
  variant_count?: number;
  parent_phenotype?: Record<string, unknown> | null;
  child_phenotypes?: Record<string, unknown>[] | null;
  evidence?: Record<string, unknown>[] | null;
}

export interface PhenotypeUpdate {
  name?: string | null;
  definition?: string | null;
  synonyms?: string[] | null;
  category?: 'congenital' | 'developmental' | 'neurological' | 'cardiovascular' | 'musculoskeletal' | 'endocrine' | 'immunological' | 'oncological' | 'other' | null;
  parent_hpo_id?: string | null;
  is_root_term?: boolean | null;
  frequency_in_med13?: string | null;
  severity_score?: number | null;
}

export interface AuthorInfo {
  name: string;
  first_name?: string | null;
  last_name?: string | null;
  affiliation?: string | null;
  orcid?: string | null;
}

export interface PublicationCreate {
  title: string;
  authors: AuthorInfo[];
  journal: string;
  publication_year: number;
  pubmed_id?: string | null;
  pmc_id?: string | null;
  doi?: string | null;
  volume?: string | null;
  issue?: string | null;
  pages?: string | null;
  publication_date?: string | null;
  publication_type?: 'journal_article' | 'review_article' | 'case_report' | 'conference_abstract' | 'book_chapter' | 'thesis' | 'preprint';
  abstract?: string | null;
  keywords?: string[] | null;
  citation_count?: number | null;
  impact_factor?: number | null;
  reviewed?: boolean;
  relevance_score?: number | null;
  full_text_url?: string | null;
  open_access?: boolean;
}

export interface PublicationResponse {
  id: number;
  pubmed_id?: string | null;
  pmc_id?: string | null;
  doi?: string | null;
  title: string;
  authors: AuthorInfo[];
  journal: string;
  publication_year: number;
  volume?: string | null;
  issue?: string | null;
  pages?: string | null;
  publication_date?: string | null;
  publication_type: 'journal_article' | 'review_article' | 'case_report' | 'conference_abstract' | 'book_chapter' | 'thesis' | 'preprint';
  abstract?: string | null;
  keywords?: string[] | null;
  citation_count?: number | null;
  impact_factor?: number | null;
  reviewed: boolean;
  relevance_score?: number | null;
  full_text_url?: string | null;
  open_access: boolean;
  created_at: string;
  updated_at: string;
  evidence_count?: number;
  evidence?: Record<string, unknown>[] | null;
}

export interface PublicationUpdate {
  pubmed_id?: string | null;
  pmc_id?: string | null;
  doi?: string | null;
  title?: string | null;
  authors?: AuthorInfo[] | null;
  abstract?: string | null;
  keywords?: string[] | null;
  volume?: string | null;
  issue?: string | null;
  pages?: string | null;
  publication_date?: string | null;
  citation_count?: number | null;
  impact_factor?: number | null;
  reviewed?: boolean | null;
  relevance_score?: number | null;
  full_text_url?: string | null;
  open_access?: boolean | null;
}

export interface VariantCreate {
  gene_id: string;
  chromosome: string;
  position: number;
  reference_allele: string;
  alternate_allele: string;
  clinvar_id?: string | null;
  variant_id?: string | null;
  hgvs_genomic?: string | null;
  hgvs_protein?: string | null;
  hgvs_cdna?: string | null;
  variant_type?: 'snv' | 'indel' | 'cnv' | 'structural' | 'unknown';
  clinical_significance?: 'pathogenic' | 'likely_pathogenic' | 'uncertain_significance' | 'likely_benign' | 'benign' | 'conflicting' | 'not_provided';
  condition?: string | null;
  review_status?: string | null;
  allele_frequency?: number | null;
  gnomad_af?: number | null;
}

export interface VariantResponse {
  id: number;
  variant_id: string;
  clinvar_id?: string | null;
  gene_id: string;
  gene_symbol: string;
  chromosome: string;
  position: number;
  reference_allele: string;
  alternate_allele: string;
  hgvs_genomic?: string | null;
  hgvs_protein?: string | null;
  hgvs_cdna?: string | null;
  variant_type: 'snv' | 'indel' | 'cnv' | 'structural' | 'unknown';
  clinical_significance: 'pathogenic' | 'likely_pathogenic' | 'uncertain_significance' | 'likely_benign' | 'benign' | 'conflicting' | 'not_provided';
  condition?: string | null;
  review_status?: string | null;
  allele_frequency?: number | null;
  gnomad_af?: number | null;
  created_at: string;
  updated_at: string;
  evidence_count?: number;
  gene?: Record<string, unknown> | null;
  evidence?: Record<string, unknown>[] | null;
}

export interface VariantUpdate {
  clinvar_id?: string | null;
  hgvs_genomic?: string | null;
  hgvs_protein?: string | null;
  hgvs_cdna?: string | null;
  variant_type?: 'snv' | 'indel' | 'cnv' | 'structural' | 'unknown' | null;
  clinical_significance?: 'pathogenic' | 'likely_pathogenic' | 'uncertain_significance' | 'likely_benign' | 'benign' | 'conflicting' | 'not_provided' | null;
  condition?: string | null;
  review_status?: string | null;
  allele_frequency?: number | null;
  gnomad_af?: number | null;
}
